mailhog:
  image: mailhog/mailhog
  ports:
    - "8025:8025"

neo4j:
  image: neo4j:2.3
  volumes:
    - /mnt/sda1/data/immercv/neo4j:/data
  ulimits:
    nofile:
      soft: 40000
      hard: 40000
  environment:
    NEO4J_AUTH: neo4j/password
  ports:
    - "7473:7473"
    - "7474:7474"

postgres:
  image: postgres:9.4
  volumes:
    # If you are using boot2docker, postgres data has to live in the VM for now until #581 is fixed
    # for more info see here: https://github.com/boot2docker/boot2docker/issues/581
    - /mnt/sda1/data/immercv/postgres:/var/lib/postgresql/data
  ports:
    - "5432:5432"

django:
  dockerfile: Dockerfile-dev
  build: .
  command: bash -c "source check_up_containers.bash; cat /etc/hosts; sleep 5; ping -c3 postgres; check_up postgres postgres 5432; check_up neo4j neo4j 7474; python /app/manage.py runserver_plus 0.0.0.0:8000"
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  links:
    - mailhog
    - neo4j
    - postgres
